### ISSUE TITLE
some unused files and registration false stated

### ISSUE THREAD

**Issue by meghakundu** [erhanurgun/YTB06-ninja-laravel-project#2]
The files related to "kebabs" and "registration" mentioned false is not clear. @erhanurgun  Kindly guide about what else features to be included, otherwise can make this to only mobile app.

**Comment by erhanurgun** [comment]
> The files related to "kebabs" and "registration" mentioned false is not clear. @erhanurgun Kindly guide about what else features to be included, otherwise can make this to only mobile app.

I wrote this project on the occasion of NetNinja youtube channel (https://youtube.com/@NetNinja) to reinforce laravel and added it to github... I plan to remove unnecessary projects from github, I have always postponed it because I need to make time for it. As soon as possible I will clean the unnecessary remnants from my github account...

**Comment by meghakundu** [comment]
> > The files related to "kebabs" and "registration" mentioned false is not clear. @erhanurgun Kindly guide about what else features to be included, otherwise can make this to only mobile app.
> 
> I wrote this project on the occasion of NetNinja youtube channel (https://youtube.com/@NetNinja) to reinforce laravel and added it to github... I plan to remove unnecessary projects from github, I have always postponed it because I need to make time for it. As soon as possible I will clean the unnecessary remnants from my github account...

Thanks for the info.
